/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CyberChip: typeof import('./components/shared/CyberChip.vue')['default']
    CyberDatepicker: typeof import('./components/shared/CyberDatepicker.vue')['default']
    CyberHeader: typeof import('./components/shared/CyberHeader.vue')['default']
    GenericDetail: typeof import('./components/generic/GenericDetail.vue')['default']
    GenericFilter: typeof import('./components/generic/GenericFilter.vue')['default']
    GenericForm: typeof import('./components/generic/GenericForm.vue')['default']
    GenericList: typeof import('./components/generic/GenericList.vue')['default']
    MonitorPanel: typeof import('./components/dashboard/MonitorPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./components/dashboard/StatCard.vue')['default']
  }
}
