<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FiveamTechCv.Abstract\FiveamTechCv.Abstract.csproj" />
      <ProjectReference Include="..\FiveamTechCv.Graph\FiveamTechCv.Graph.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.GenAI" Version="0.13.0" />
      <PackageReference Include="HotChocolate.AspNetCore" Version="13.9.15" />
      <PackageReference Include="HotChocolate.Data.Neo4J" Version="13.9.15" />
      <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
      <PackageReference Include="Neo4j.Driver" Version="5.25.0" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    </ItemGroup>

</Project>
